name: CD

on:
  release:
    types: [ created ]

concurrency:
  group: "cd"
  cancel-in-progress: false

env:
  GRADLE_OPTS: -Dorg.gradle.parallel=true -Dorg.gradle.caching=true

jobs:
  build:
    runs-on: macos-latest

    permissions:
      contents: read

    environment: CD

    steps:
      - name: Set environment for version
        run: long="${{ github.ref }}"; version=${long#"refs/tags/v"}; echo "version=${version}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2
      - name: Publish
        run: ./gradlew -Pversion=$version -Dorg.gradle.parallel=false publish closeAndReleaseStagingRepository
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONARTYPE_APIKEY }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONARTYPE_APITOKEN }}
