name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: -Dorg.gradle.parallel=true -Dorg.gradle.caching=true

jobs:
  build:
    runs-on: macos-14
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true
          gradle-home-cache-cleanup: true
      - name: Build with Gradle
        run: ./gradlew javaToolchains
